"use client";
import Navbar from "@/components/navbar/page";
import { store } from "@/redux/store/store";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "NirvaPay",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <Navbar />

          {children}
        </Provider>
      </body>
    </html>
  );
}
